import * as React from "react";
import { Component, CSSProperties } from "react";
import { cx } from "emotion";

import "./fonts/jimo.css";

import fontsDict from "./fonts";

export type IconType = "lg" | "2x" | "3x" | "4x" | "5x";

export interface IconProps {
  name: EJimoIcon;
  className?: string;
  style?: CSSProperties;
  onClick?: (event: React.MouseEvent) => void;
  onMouseEnter?: (event: React.MouseEvent) => void;
}

let iconPrefix = "jimo-icon";

let JimoIcon: React.FC<IconProps> = (props) => {
  let classNames = iconPrefix;

  classNames = props.className ? cx(classNames, props.className) : classNames;

  return (
    <i
      style={props.style}
      className={classNames}
      aria-hidden="true"
      onMouseEnter={props.onMouseEnter}
      onClick={props.onClick}
      dangerouslySetInnerHTML={{ __html: `&#${fontsDict[props.name]}` || `NONE:${props.name}` }}
    ></i>
  );
};

export default JimoIcon;

export enum EJimoIcon {
  // icons list
  application = "application",
  appsOverview = "apps-overview",
  bellOutline = "bell-outline",
  calendar = "calendar",
  checkbox = "checkbox",
  permissions = "permissions",
  batch = "batch",
  checkCircleOutline = "check-circle-outline",
  checkInfo = "check-info",
  clock = "clock",
  configurationCenter = "configuration-center",
  dataAnalysis = "data-analysis",
  defectAnalysis = "defect-analysis",
  device = "device",
  download = "download",
  emptyData = "empty-data",
  envelope = "envelope",
  envelopeOpen = "envelope-open",
  flowControlAnalysis = "flow-control-analysis",
  eye = "eye",
  fullscreen = "fullscreen",
  gauge = "gauge",
  incomingInspection = "incoming-inspection",
  inspection = "inspection",
  intelligentReport = "intelligent-report",
  inventory = "inventory",
  rebind = "rebind",
  leftAngleCircle = "left-angle-circle",
  loading = "loading",
  measurementDataAnalysis = "measurement-data-analysis",
  mechanicalAnalysis = "mechanical-analysis",
  mobile = "mobile",
  packing = "packing",
  play = "play",
  plus = "plus",
  ppap = "ppap",
  problemAnalysis = "problem-analysis",
  processEvents = "process-events",
  product = "product",
  productInformationManagement = "product-information-management",
  productionManagement = "production-management",
  productionProcess = "production-process",
  productTraceability = "product-traceability",
  purchasingManagement = "purchasing-management",
  qualityProblemTracking = "quality-problem-tracking",
  questionCircle = "question-circle",
  quit = "quit",
  requirements = "requirements",
  retry = "retry",
  salesManagement = "sales-management",
  select = "select",
  serialNumber = "serial-number",
  shanghaiElectric = "shanghai-electric",
  shipmentsDetection = "shipments-detection",
  slimCross = "slim-cross",
  tableHorizontal = "table-horizontal",
  tableVertical = "table-vertical",
  tick = "tick",
  toolingManagement = "tooling-management",
  upload = "upload",
  uploadBox = "upload-box",
  users = "users",
  organization = "organization",
  moreMenu = "more-menu",
  warnCircleOutline = "warn-circle-outline",
  wechat = "wechat",
  wechatCircle = "wechat-circle",
  zoomIn = "zoom-in",
  zoomOut = "zoom-out",
  ipc = "ipc",
  scan = "scan",
  tickEmbossed = "tick-embossed",
  crossEmbossed = "cross-embossed",
  infoEmbossed = "info-embossed",
  questionCircleOutline = "question-circle-outline",
  ellipsisHorizontal = "ellipsis-horizontal",
  warehouseIn = "warehouse-in",
  warehouseOut = "warehouse-out",
  warehouseTransfer = "warehouse-transfer",
  warehouseCheck = "warehouse-check",
  worker = "worker",
  switchCircle = "switch-circle",
  trash = "trash",
  rightAngleCircle = "right-angle-circle",
  textFile = "text-file",
  listFile = "list-file",
  layers = "layers",
  workingShift = "working-shift",
  user = "user",
  search = "search",
  cancelCircle = "cancel-circle",
  playEmbossed = "play-embossed",
  warnEmbossed = "warn-embossed",
  alarm = "alarm",
  sort = "sort",
  menuPushLeft = "menu-push-left",
  menuPushRight = "menu-push-right",
  salary = "salary",
  cancelSquare = "cancel-square",
  checkSquare = "check-square",
  editSquare = "edit-square",
  button = "button",
  container = "container",
  input = "input",
  numberInput = "number-input",
  radio = "radio",
  switch = "switch",
  textArea = "text-area",
  layersFilled = "layers-filled",
  circleReport = "circle-report",
  bellFilled = "bell-filled",
  profileConfig = "profile-config",
  profileMenu = "profile-menu",
  sharing = "sharing",
  starBoxed = "star-boxed",
  loudspeakerEmbossed = "loudspeaker-embossed",
  taskEmbossed = "task-embossed",
  deleteCircle = "delete-circle",
  editCircle = "edit-circle",
  location = "location",
  delete = "delete",
  starFilled = "star-filled",
  star = "star",
  customer = "customer",
  fileRule = "file-rule",
  folder = "folder",
  history = "history",
  materialInformation = "material-information",
  process = "process",
  productBom = "product-bom",
  leftSquareOutline = "left-square-outline",
  rightSquareOutline = "right-square-outline",
  deviceList = "device-list",
  deviceCategory = "device-category",
  edgeDevice = "edge-device",
  report = "report",
  bookmarkOutline = "bookmark-outline",
  cube = "cube",
  taskCheckEmbossed = "task-check-embossed",
  progressOutline = "progress-outline",
  warning = "warning",
  angleDownOutline = "angle-down-outline",
  documentList = "document-list",
  documentCategory = "document-category",
  dataRestore = "data-restore",
  roleConfig = "role-config",
  searchModule = "search-module",
  start = "start",
  rebindCode = "rebind-code",
  pdfFile = "pdf-file",
  imageFile = "image-file",
  excelFile = "excel-file",
  wordFile = "word-file",
  fileStatus = "file-status",
  clockEmbossed = "clock-embossed",
  keyboard = "keyboard",
  orderNumber = "order-number",
  samplingMethod = "sampling-method",
  linearWorker = "linear-worker",
  details = "details",
  warehouse = "warehouse",
  overallDecision = "overall-decision",
  userFilled = "user-filled",
  enterprise = "enterprise",
  locked = "locked",
  workerOutline = "worker-outline",
  advancedSearch = "advanced-search",
  print = "print",
  orderSynergy = "order-synergy",
  clientRelation = "client-relation",
  label = "label",
  boardMonitor = "board-monitor",
  reportManagement = "report-management",
  logistics = "logistics",
  remark = "remark",
  part = "part",
  production = "production",
  supplier = "supplier",
  tag = "tag",
  team = "team",
  traceCode = "trace-code",
  authority = "authority",
  creationUserEmbossed = "creation-user-embossed",
  pieChart = "pie-chart",
  pieceworkCalculation = "piecework-calculation",
  checkFilled = "check-filled",
  clockFilled = "clock-filled",
  pieOutline = "pie-outline",
  userAddFilled = "user-add-filled",
  userSettingOutline = "user-setting-outline",
  // icons list
}
